federation:
  name: syntax_validator_network
  nodes:
    - address: 192.168.1.101:50051
      role: coordinator
      shard_range: 0-511
    - address: 192.168.1.102:50051  
      role: worker
      shard_range: 512-1023

training:
  batch_size: 256
  epochs: 100
  aggregation:
    interval: 300
    method: secure_aggregation
    differential_privacy:
      epsilon: 0.5
      delta: 1e-6

model:
  architecture: transformer
  params:
    num_layers: 12
    hidden_size: 768
    attention_heads: 12
