federation:
  name: syntax_validator_network
  nodes:
    - address: 192.168.1.101:50051
      role: coordinator
      shard_range: [0, 511]
      security_level: 3
    - address: 192.168.1.102:50051  
      role: worker
      shard_range: [512, 1023]
      security_level: 2

validation_metrics:
  simd_acceleration: 1.3x
  actor_throughput: 10k/s
  onnx_latency: 50ms
  fault_recovery: 60s

monitoring:
  prometheus_endpoint: http://localhost:9090
  scrape_interval: 15s
