stages:
  - build
  - test
  - verify
  - deploy

variables:
  LLVM_PATH: "/opt/compiler/llvm"

build_image:
  stage: build
  script:
    - cd quantum-compiler
    - ./build.sh -t Release
    - docker build -t quantum-env -f Dockerfile.quantum .
  tags:
    - docker

unit_test:
  stage: test
  script:
    - python3 -m pytest tests/unit --junitxml=unit_report.xml
  artifacts:
    reports:
      junit: unit_report.xml

formal_verification:
  stage: verify
  script:
    - $LLVM_PATH/bin/clang-18 --verify phase1/formal_verification/memory_model.als
    - alloy compile hybrid_memory.als --verifier=Alloy4
    - alloy check HybridSafety --max-trace=5
  artifacts:
    paths:
      - verification_report.alloy

deploy_prod:
  stage: deploy
  script:
    - kubectl apply -f k8s-deployment.yaml
  only:
    - master
