FROM nvidia/cuda:12.2.0-base-ubuntu22.04

RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    software-properties-common \
    cuda-toolkit-12-2 \
    nvidia-driver-535 \
    libcudnn8 \
    libavx512-dev \          # AVX1024替换为AVX512
    gcc-12-plugin-dev \
    valgrind \
    python3.10-dev \
    && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
    && echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" >> /etc/apt/sources.list.d/llvm.list \
    && apt-get update && apt-get install -y \
    clang-18 \
    llvm-18 \
    qiskit-symbex \
    qsharp \
    libdilithium3 \
    libopenblas-dev \
    openmpi-bin libopenmpi-dev \
    intel-mkl-2023.2 \
    cython \
    onnxruntime \
    locust \
    prometheus \
    hwloc \
    numactl

RUN git clone https://github.com/quantum-math/cholesky-cuda \
    && cd cholesky-cuda && make install

RUN pip3 install \
    qiskit==0.43.0 \
    qiskit-aer==0.12.1 \
    cupy-cuda12x \
    torch==2.1.0 \
    torchvision==0.16.0 \
    torchaudio==2.1.0 \
    tensorflow-quantum==1.0.0 \
    onnxruntime==1.15.0 \
    protoactor==2.3.1 \
    locust==2.15.1 \
    cython==3.0.0 \
    numba==0.57.0 \
    mpi4py==3.1.4 \
    py-cpuinfo==9.0.0 \
    pennylane \
    transformers

ENV QISKIT_IBM_TOKEN="YOUR_API_TOKEN"
ENV QSHARP_PACKAGES="/opt/qsharp-packages"
ENV LD_LIBRARY_PATH="/opt/intel/mkl/lib/intel64:/usr/local/cuda-12.2/lib64:$LD_LIBRARY_PATH"
ENV OMP_NUM_THREADS=1
ENV PATH="/usr/local/cuda-12.2/bin:$PATH"
ENV CFLAGS='-march=native -O3 -mavx512f'  # 替换为AVX512
ENV PYTHONPATH="/phase4/math:$PYTHONPATH"

COPY . /phase4
WORKDIR /workspace

CMD ["/bin/bash"]
